version: '3'
services:
  node:
    # Dockerfileの場所
    build:
      context: .
      dockerfile: ./container/nuxt_dev/Dockerfile
    working_dir: /home/node/app/project
    # ホストOSとコンテナ内でソースコードを共有する
    volumes:
      - ./:/home/node/app
    # コンテナ内部の3000を外部から5000でアクセスする
    ports:
      - 5000:3000
    environment:
      - HOST=0.0.0.0
    command: yarn run dev
